version: "3.8"

services:
  texttospeechbackend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: textToSpeechBackend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    networks:
      - mongo-network

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network

volumes:
  mongo-data:

networks:
  mongo-network:
    driver: bridge
