services:
  texttospeechbackend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: textToSpeechBackend
    restart: always
    depends_on:
      - mongodb
      - minio
    ports:
      - "8080:8080"
    networks:
      - backend-network
    environment:
      SPRING_APPLICATION_NAME: TextToSpeech
      SPRING_SECURITY_USER_NAME: root
      SPRING_SECURITY_USER_PASSWORD: root
      SERVER_PORT: 8080

      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/asr_thai_backend
      SPRING_DATA_MONGODB_DATABASE: asr_thai_backend
      MINIO_URL: bucket-production-3651.up.railway.app
      MINIO_ACCESS_KEY: Pzpf4JWDm9iRN7evIdBf
      MINIO_SECRET_KEY: lAdv1SbN7Bi34xqbsBo57vDeh61WJNOOhDSUYEAX

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - backend-network

  minio:
    image: bitnami/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: P@ssw0rd64
      MINIO_HTTP_BODY_SIZE_LIMIT: "5GB"
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - ./minio-data:/bitnami/minio/data
    networks:
      - backend-network

volumes:
  mongo-data:

networks:
  backend-network:
    driver: bridge
