spring.application.name=TextToSpeech
spring.security.user.name=root
spring.security.user.password=root
server.port=8080

spring.data.mongodb.uri=mongodb://mongodb/docker-db
spring.data.mongodb.database=asr_thai_backend

minio.url=console-production-9247.up.railway.app
# minio.accessKey=jP1YZnBWZEix5ZSBAZNC
# minio.secretKey=D5o0HeJDvMHWRjAHOYqFKftq0Yvh6AnPgEBSOHAo

# minio.accessKey=3jMAgqYMejNjYC6NfG00
# minio.secretKey=UNekmXjTxFtz2waIVC3zvAN0IBXW8mfOCqeKwMbv

minio.accessKey=Pzpf4JWDm9iRN7evIdBf
minio.secretKey=lAdv1SbN7Bi34xqbsBo57vDeh61WJNOOhDSUYEAX

spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB
server.tomcat.max-http-form-post-size=5GB
server.tomcat.max-swallow-size=5GB

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=880dc7001@smtp-brevo.com
spring.mail.password=4CBsbRvn9kYKQjwO
spring.mail.from=asrproj2024@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.properties.hibernate.connection.charSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

security.jwt.secret-key=/8N1R+MpViRLgiwrBLV+E6yXw9b7q6h7ddKR2WiD7iY=
security.jwt.expiration-time=3600000
